# Generated by Django 5.1 on 2024-12-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='account_on',
            new_name='account_no',
        ),
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_type',
            field=models.CharField(choices=[('Current', 'Current'), ('Savings', 'Savings')], max_length=10),
        ),
    ]
